urls:
  base_config: https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config?raw=true
  base_checkpoint: http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
  dataset: "https://github.com/s-collins/ua_vision_data/archive/dataset1.tar.gz"

dirs:

  pipeline: pipeline
  base_model: base_model
  base_model_checkpoint: base_model/checkpoint
  raw_data: raw_data

paths:
  base_config: base_model/pipeline.config
  updated_config: pipeline/pipeline.config

#------------------------------------------------------------------------------
# object_detection config file settings
#------------------------------------------------------------------------------

config:

  label_map_path: TEST_PATH

  model:
    model_type: ssd
    num_classes: 1

  train_config:
    fine_tune_checkpoint: base_model/checkpoint/model.ckpt
    num_steps: 100

  train_input_reader:
    tf_record_input_reader:
      input_path: TEST_PATH

  eval_config:
    num_examples: 60

  eval_input_reader:
    tf_record_input_reader:
      input_path: TEST_PATH

