urls:
  base_config: https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_mobilenet_v1_pets.config?raw=true
  base_checkpoint: http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
  dataset: https://github.com/s-collins/ua_vision_data/releases/download/dataset1/dataset1.tar.gz

dirs:

  pipeline: pipeline
  test_images: pipeline/input/test_images
  eval_images: pipeline/input/eval_images
  output: pipeline/output
  base_model: base_model
  base_model_checkpoint: base_model/ssd_mobilenet_v1_coco_2018_01_28
  raw_data: dataset1

paths:
  base_config: base_model/pipeline.config
  updated_config: pipeline/pipeline.config
  train_script: /home/paperspace/training/tensorflow/models/research/object_detection/legacy/train.py

training_ratio: 0.8

labels:
  - 

#------------------------------------------------------------------------------
# object_detection config file settings
#------------------------------------------------------------------------------

config:

  label_map_path: pipeline/input/label_map.pbtxt

  model:
    model_type: ssd
    num_classes: 1

  train_config:
    fine_tune_checkpoint: base_model/ssd_mobilenet_v1_coco_2018_01_28/model.ckpt
    num_steps: 2000

  train_input_reader:
    tf_record_input_reader:
      input_path: pipeline/input/test.tfrecords

  eval_config:
    num_examples: 60

  eval_input_reader:
    tf_record_input_reader:
      input_path: pipeline/input/eval.tfrecords
